### PR TITLE
Go Live

### PR DESCRIPTION
**Pull request by thelamer**
Initial version , the only thing to store locally for this is plugin configs if they are setup. Other than that for this app everything is stored in browser cache.

For armhf and aarch I stashed phantomjs blobs in our object storage.

### CODE REVIEW

**Comment by sparklyballs** [comment]
should probably use absolute paths for the cleanup routine

https://github.com/linuxserver/docker-dillinger/blob/2ca658f2ba5a65a2a346409eada092c0b82de03c/Dockerfile#L42

future proof against someone sticking a cd to an alternative root folder, and it's prudent anyways.

**Comment by CHBMB** [comment]
@thelamer I'll test this in a while, might see if I can use that phatomjs bin in [codimd](https://github.com/linuxserver/docker-codimd).  That's an issue I've had with the `armhf` and `aarch64` builds there too.

**Comment by CHBMB** [comment]
Built and tested locally, working fine, one thing I wondered about, is it worth including either/both sample config.json files for the [plugins?](https://github.com/joemccann/dillinger#plugins) or checking for the presence of environmental variables starting with either
```
dropbox
github
googledrive
onedrive
medium
```
and then if present adding them to the npm run, I did something similar in CodiMD and I quite liked the approach, as gives the end user the ability to either configure using a json file (example already present) or by adding environmental variables.

[Something like this for each plugin](https://github.com/linuxserver/docker-codimd/blob/master/root/etc/cont-init.d/30-config#L43)
[Then construct the npm run routine](https://github.com/linuxserver/docker-codimd/blob/master/root/etc/services.d/codimd/run#L15)

**Comment by thelamer** [comment]
@CHBMB normally I would be all for it but two problems: 
1. We do not know what will be in that directory in future releases
2. We do not know what the format of the files will be for future release (little stretch here don't see it changing but still)

By stopping at the directory symlink we futureproof it, and advanced users can play around with it. 
If a plugin gains such a dependance or level of popularity we need env vars to configure it in k8 clusters etc, then we should cross that bridge when it arises not add logic for an initial release. 
IMPO

**Comment by CHBMB** [comment]
@thelamer OK, fair enough, that makes sense to me, just spitballing ideas.

**Review by CHBMB — APPROVED** [review]

**Pull request merged**
